---
- hosts: personal
  tasks: 
  - name: Install barebones dev tools
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - curl
      - vim-nox
      - git
      - zsh
    sudo: yes
    register: barebonesInstalled
    notify:
    - something stupid


  - include: tasks/workspace.yml

  - include: tasks/ohmyzsh.yml

  - include: tasks/vim.yml

  - name: setup aws creds
    command: echo {{ creds }} > ~/FAKECREDS
    
  handlers:
  - name: something stupid
    service: name=puppet state=stopped

