---
- hosts: personal
  sudo: yes
  #TODO: move sudo to become using sudo
  # TODO: Initialize locale with  sudo locale-gen en_GB.UTF-8
  roles:
    - franklinklim.docker
    - franklinklim.docker-compose
  vars:
    docker_compose_version: 1.5.1
  tasks: 
  - name: Install barebones dev tools
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - curl
      - vim-nox
      - git
      - zsh
    register: barebonesInstalled
    notify:
    - something stupid


  - include: tasks/workspace.yml

  - include: tasks/ohmyzsh.yml

  - include: tasks/vim.yml

  - include: tasks/mytools.yml

  - name: setup aws creds
    command: echo {{ creds }} > ~/FAKECREDS
    
  handlers:
  - name: something stupid
    service: name=puppet state=stopped

    #TODO: fix locale on the machine with 
    # update-locale LANG=en_GB.UTF-8 LC_MESSAGES=POSIX
