
  - name: get apps from source code
    git: repo={{item.repo}}
         dest={{item.dest}}
    with_items:
      - { repo: "https://github.com/wakaru44/my_dockerplace.git",
          dest: "/home/ubuntu/apps/my_dockerplace"}
      - { repo: "https://github.com/wakaru44/docker.ui.git",
          dest: "/home/ubuntu/apps/docker.ui"}
      - { repo: "https://github.com/francescou/docker-compose-ui.git",
        dest: "/home/ubuntu/apps/docker-compose-ui"}
