
#TODO: this structure is created (wrongly) as root. fix it.

  - name: Create structure
    become: no
    file: path=~/{{item}} state=directory
    with_items:
      - workspace/src
      - workspace
      - Software
      - apps
    #file: path=~/workspace/src state=directory
    #file: path=~/Software state=directory
    #file: path=~/apps state=directory
    #file: path=~/zzzzAnsible state=directory
    register: structureCreated

  - name: get projects
    become: no
    git: repo={{item.repo}}
         dest={{item.dest}}
    with_items:
      - { "repo": "https://github.com/wakaru44/ansible.sbs_provision.git",
                "dest": "~/workspace/src/github.com/wakaru44/ansible.sbs_provision" }
      - { "repo": "https://github.com/wakaru44/api_ab_test.git",
                "dest": "~/workspace/src/github.com/wakaru44/api_ab_test" }
      - { "repo": "https://github.com/wakaru44/aws_lambda.python_boilerplate.git",
                "dest": "~/workspace/src/github.com/wakaru44/aws_lambda.python_boilerplate" }
      - { "repo": "https://github.com/wakaru44/aws_lambda.sbs_api_base.git",
                "dest": "~/workspace/src/github.com/wakaru44/aws_lambda.sbs_api_base" }
      - { "repo": "https://github.com/wakaru44/capitulizer.git",
                "dest": "~/workspace/src/github.com/wakaru44/capitulizer" }
      - { "repo": "https://github.com/wakaru44/chrome-ext-cura-a-la-insensibilidad.git",
                "dest": "~/workspace/src/github.com/wakaru44/chrome-ext-cura-a-la-insensibilidad" }
      - { "repo": "https://github.com/wakaru44/chrome-ext-venezuela-no-more.git",
                "dest": "~/workspace/src/github.com/wakaru44/chrome-ext-venezuela-no-more" }
      - { "repo": "https://github.com/wakaru44/composefiles.git",
                "dest": "~/workspace/src/github.com/wakaru44/composefiles" }
      - { "repo": "https://github.com/wakaru44/cordova.sbs_mobile_app.git",
                "dest": "~/workspace/src/github.com/wakaru44/cordova.sbs_mobile_app" }
      - { "repo": "https://github.com/wakaru44/docker-minecraft-client.git",
                "dest": "~/workspace/src/github.com/wakaru44/docker-minecraft-client" }
      - { "repo": "https://github.com/wakaru44/docker.flask_service_boilerplate.git",
                "dest": "~/workspace/src/github.com/wakaru44/docker.flask_service_boilerplate" }
      - { "repo": "https://github.com/wakaru44/docker.sbs_api_extend.git",
                "dest": "~/workspace/src/github.com/wakaru44/docker.sbs_api_extend" }
      - { "repo": "https://github.com/wakaru44/docker.url_check_service.git",
                "dest": "~/workspace/src/github.com/wakaru44/docker.url_check_service" }
      - { "repo": "https://github.com/wakaru44/dvorak_spanish_layout.git",
                "dest": "~/workspace/src/github.com/wakaru44/dvorak_spanish_layout" }
      - { "repo": "https://github.com/wakaru44/flask.sbs_api_extend.git",
                "dest": "~/workspace/src/github.com/wakaru44/flask.sbs_api_extend" }
      - { "repo": "https://github.com/wakaru44/flask_service_boilerplate.git",
                "dest": "~/workspace/src/github.com/wakaru44/flask_service_boilerplate" }
      - { "repo": "https://github.com/wakaru44/kali-cloud-build.git",
                "dest": "~/workspace/src/github.com/wakaru44/kali-cloud-build" }
      - { "repo": "https://github.com/wakaru44/minitools.git",
                "dest": "~/workspace/src/github.com/wakaru44/minitools" }
      - { "repo": "https://github.com/wakaru44/my_dockerplace.git",
                "dest": "~/workspace/src/github.com/wakaru44/my_dockerplace" }
      - { "repo": "https://github.com/wakaru44/neural-style.git",
                "dest": "~/workspace/src/github.com/wakaru44/neural-style" }
      - { "repo": "https://github.com/wakaru44/qwerty-dvorak-converter.git",
                "dest": "~/workspace/src/github.com/wakaru44/qwerty-dvorak-converter" }
      - { "repo": "https://github.com/wakaru44/radiofaba.git",
                "dest": "~/workspace/src/github.com/wakaru44/radiofaba" }
      - { "repo": "https://github.com/wakaru44/sensu-docker.git",
                "dest": "~/workspace/src/github.com/wakaru44/sensu-docker" }
      - { "repo": "https://github.com/wakaru44/shinken.shiping.git",
                "dest": "~/workspace/src/github.com/wakaru44/shinken.shiping" }
      - { "repo": "https://github.com/wakaru44/thetasploiter.git",
                "dest": "~/workspace/src/github.com/wakaru44/thetasploiter" }
      - { "repo": "https://github.com/wakaru44/troposphere.sbs_infrastructure.git",
                "dest": "~/workspace/src/github.com/wakaru44/troposphere.sbs_infrastructure" }
      - { "repo": "https://github.com/wakaru44/try_git.git",
                "dest": "~/workspace/src/github.com/wakaru44/try_git" }
      - { "repo": "https://github.com/wakaru44/url_check_service.git",
                "dest": "~/workspace/src/github.com/wakaru44/url_check_service" }
      - { "repo": "https://github.com/wakaru44/vimrc.git",
                "dest": "~/workspace/src/github.com/wakaru44/vimrc" }
      - { "repo": "https://github.com/juanantoniofm/accesible-moodle.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/accesible-moodle" }
      - { "repo": "https://github.com/juanantoniofm/ansible.nginx_role.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/ansible.nginx_role" }
      - { "repo": "https://github.com/juanantoniofm/blog.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/blog" }
      - { "repo": "https://github.com/juanantoniofm/chigrin.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/chigrin" }
      - { "repo": "https://github.com/juanantoniofm/code-by-voice.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/code-by-voice" }
      - { "repo": "https://github.com/juanantoniofm/docker.apprecious.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/docker.apprecious" }
      - { "repo": "https://github.com/juanantoniofm/docker.orientdb.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/docker.orientdb" }
      - { "repo": "https://github.com/juanantoniofm/exercise.trinode.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/exercise.trinode" }
      - { "repo": "https://github.com/juanantoniofm/FliKISS.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/FliKISS" }
      - { "repo": "https://github.com/juanantoniofm/goapi.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/goapi" }
      - { "repo": "https://github.com/juanantoniofm/greaper.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/greaper" }
      - { "repo": "https://github.com/juanantoniofm/kafka-campc.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/kafka-campc" }
      - { "repo": "https://github.com/juanantoniofm/kafka-dockerized-cluster.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/kafka-dockerized-cluster" }
      - { "repo": "https://github.com/juanantoniofm/oh-my-zsh.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/oh-my-zsh" }
      - { "repo": "https://github.com/juanantoniofm/pizza-py-party.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/pizza-py-party" }
      - { "repo": "https://github.com/juanantoniofm/pycomplexity.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/pycomplexity" }
      - { "repo": "https://github.com/juanantoniofm/pythoniter.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/pythoniter" }
      - { "repo": "https://github.com/juanantoniofm/radiofaba.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/radiofaba" }
      - { "repo": "https://github.com/juanantoniofm/recopilatron.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/recopilatron" }
      - { "repo": "https://github.com/juanantoniofm/wakarudacity-cs253.git",
                "dest": "~/workspace/src/github.com/juanantoniofm/wakarudacity-cs253" }
