
#TODO: this structure is created (wrongly) as root. fix it.

  - name: Create structure
    file: path=~/{{item}} state=directory
    with_items:
      - workspace/src
      - workspace
      - Software
      - apps
    #file: path=~/workspace/src state=directory
    #file: path=~/Software state=directory
    #file: path=~/apps state=directory
    #file: path=~/zzzzAnsible state=directory
    register: structureCreated

  - name: get projects
    git: repo={{item.repo}}
         dest={{item.dest}}
    with_items:
      - { "repo": https://github.com/juanantoniofm/accesible-moodle.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/accesible-moodle },
      - { "repo": https://github.com/juanantoniofm/ansible.nginx_role.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/ansible.nginx_role },
      - { "repo": https://github.com/juanantoniofm/blog.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/blog },
      - { "repo": https://github.com/juanantoniofm/chigrin.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/chigrin },
      - { "repo": https://github.com/juanantoniofm/code-by-voice.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/code-by-voice },
      - { "repo": https://github.com/juanantoniofm/docker.apprecious.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/docker.apprecious },
      - { "repo": https://github.com/juanantoniofm/docker.orientdb.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/docker.orientdb },
      - { "repo": https://github.com/juanantoniofm/exercise.trinode.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/exercise.trinode },
      - { "repo": https://github.com/juanantoniofm/FliKISS.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/FliKISS },
      - { "repo": https://github.com/juanantoniofm/goapi.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/goapi },
      - { "repo": https://github.com/juanantoniofm/greaper.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/greaper },
      - { "repo": https://github.com/juanantoniofm/kafka-campc.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/kafka-campc },
      - { "repo": https://github.com/juanantoniofm/kafka-dockerized-cluster.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/kafka-dockerized-cluster },
      - { "repo": https://github.com/juanantoniofm/oh-my-zsh.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/oh-my-zsh },
      - { "repo": https://github.com/juanantoniofm/pizza-py-party.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/pizza-py-party },
      - { "repo": https://github.com/juanantoniofm/pycomplexity.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/pycomplexity },
      - { "repo": https://github.com/juanantoniofm/pythoniter.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/pythoniter },
      - { "repo": https://github.com/juanantoniofm/radiofaba.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/radiofaba },
      - { "repo": https://github.com/juanantoniofm/recopilatron.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/recopilatron },
      - { "repo": https://github.com/juanantoniofm/wakarudacity-cs253.git,
            "dest": /home/ubuntu/workspace/src/github.com/juanantoniofm/wakarudacity-cs253 },
