

  - name: Create structure
    file: path=~/{{item}} state=directory
    with_items:
      - workspace/src
      - workspace
      - Software
      - apps
    #file: path=~/workspace/src state=directory
    #file: path=~/Software state=directory
    #file: path=~/apps state=directory
    #file: path=~/zzzzAnsible state=directory
    register: structureCreated

  - name: get projects
    git: repo={{item.repo}}
         dest={{item.dest}}
    with_items:
      - { repo: "https://github.com/wakaru44/ansible.personal.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/ansible.personal" }
      - { repo: "https://github.com/wakaru44/api_ab_test.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/api_ab_test" }
      - { repo: "https://github.com/wakaru44/aws_lambda.personal_api_base.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/aws_lambda.personal_api_base" }
      - { repo: "https://github.com/wakaru44/aws_lambda.python_boilerplate.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/aws_lambda.python_boilerplate" }
      - { repo: "https://github.com/wakaru44/capitulizer.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/capitulizer" }
      - { repo: "https://github.com/wakaru44/chrome-ext-cura-a-la-insensibilidad.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/chrome-ext-cura-a-la-insensibilidad" }
      - { repo: "https://github.com/wakaru44/chrome-ext-venezuela-no-more.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/chrome-ext-venezuela-no-more" }
      - { repo: "https://github.com/wakaru44/cordova.simplebuttonstack.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/cordova.simplebuttonstack" }
      - { repo: "https://github.com/wakaru44/docker-minecraft-client.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/docker-minecraft-client" }
      - { repo: "https://github.com/wakaru44/docker.flask_service_boilerplate.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/docker.flask_service_boilerplate" }
      - { repo: "https://github.com/wakaru44/docker.sbs_flask_api.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/docker.sbs_flask_api" }
      - { repo: "https://github.com/wakaru44/docker.ui.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/docker.ui" }
      - { repo: "https://github.com/wakaru44/docker.url_check_service.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/docker.url_check_service" }
      - { repo: "https://github.com/wakaru44/dvorak_spanish_layout.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/dvorak_spanish_layout" }
      - { repo: "https://github.com/wakaru44/flask.sbs_api.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/flask.sbs_api" }
      - { repo: "https://github.com/wakaru44/flask_service_boilerplate.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/flask_service_boilerplate" }
      - { repo: "https://github.com/wakaru44/minitools.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/minitools" }
      - { repo: "https://github.com/wakaru44/my_dockerplace.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/my_dockerplace" }
      - { repo: "https://github.com/wakaru44/neural-style.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/neural-style" }
      - { repo: "https://github.com/wakaru44/qwerty-dvorak-converter.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/qwerty-dvorak-converter" }
      - { repo: "https://github.com/wakaru44/radiofaba.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/radiofaba" }
      - { repo: "https://github.com/wakaru44/troposphere.workstation.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/troposphere.workstation" }
      - { repo: "https://github.com/wakaru44/try_git.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/try_git" }
      - { repo: "https://github.com/wakaru44/url_check_service.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/url_check_service" }
      - { repo: "https://github.com/wakaru44/vimrc.git",
          dest: "/home/ubuntu/workspace/src/github.com/wakaru44/vimrc" }

